timeout: 0

/Kernel (x86_64)
    protocol: limine
    if_arch: x86-64
    kaslr: no
    cmdline: pros.tests pros.init=/bin/psh
    path: boot():/boot/x86_64/kernel
    module_path: boot():/boot/x86_64/initrd

/Kernel (ARM64)
    protocol: limine
    if_arch: aarch64
    kaslr: no
    cmdline: pros.tests pros.init=/bin/psh
    path: boot():/boot/aarch64/kernel
    module_path: boot():/boot/aarch64/initrd
