timeout: 0

/Kernel (x86_64)
    protocol: limine
    if_arch: x86-64
    cmdline: pros.tests
    path: boot():/boot/kernel-x86_64
    module_path: boot():/boot/initrd.tar

/Kernel (ARM64)
    protocol: limine
    if_arch: aarch64
    cmdline: pros.tests
    path: boot():/boot/kernel-aarch64
    module_path: boot():/boot/initrd.tar
