timeout: 3

/Kernel (x86_64)
    protocol: limine
    path: boot():/boot/kernel-x86_64

/Kernel (ARM64)
    protocol: limine
    path: boot():/boot/kernel-aarch64

/Kernel (RISC-V 64)
    protocol: limine
    path: boot():/boot/kernel-riscv64

/Kernel (LoongArch 64)
    protocol: limine
    path: boot():/boot/kernel-loongarch64
